---

moodlebox_install_packages:
  - network-manager
  - net-tools
  - dhcpcd5
  - avahi-daemon
  - iptables-persistent
  - hostapd
  - dnsmasq
  - git
  - ntfs-3g
  - exfat-fuse
  - lockfile-progs
  - incron
  - nginx
  - ghostscript
  - php7.4-fpm
  - php7.4-cli
  - php7.4-common
  - php7.4-json
  - php7.4-mbstring
  - php7.4-opcache
  - php7.4-readline
  - php7.4-xmlrpc
  - php7.4-curl
  - php7.4-gd
  - php7.4-intl
  - php7.4-soap
  - php7.4-mysql
  - php7.4-xml
  - php7.4-zip
  - php7.4
  - php-apcu
