---
# MoodleBox version and release date.
moodlebox_version: '3.9.0'
moodlebox_release_date: '2020-11-08'
moodlebox_name: 'MoodleBox'

# MoodleBox hostname (taken from inventory).
moodlebox_hostname: '{{ inventory_hostname }}'

# MoodleBox top level domain name.
# URL of MoodleBox is {{ moodlebox_hostname }}.{{ moodlebox_tld }}.
moodlebox_tld: 'home'

# MoodleBox main credentials.
moodlebox_username: 'moodlebox'
moodlebox_password: 'Moodlebox4$'

# MoodleBox Wi-Fi static IP address.
moodlebox_ip_address: '10.0.0.1/24'

# MoodleBox DHCP range.
moodlebox_dhcp_range_begin: "{{ moodlebox_ip_address | ipaddr('address') | ipmath(9) }}"
moodlebox_dhcp_range_end: "{{ moodlebox_ip_address | ipaddr('address') | ipmath(253) }}"

# MoodleBox external public DNS servers IP addresses.
moodlebox_external_dns_ip_address:
  - '1.1.1.1'  # Cloudflare privacy-first DNS
  - '1.0.0.1'  # Cloudflare privacy-first DNS
  # - '84.200.69.80' # DNS.WATCH
  # - '84.200.70.40' # DNS.WATCH
  # - '64.6.64.6' # Verisign
  # - '64.6.65.6' # Verisign

# MoodleBox db credentials.
moodlebox_db_username: '{{ moodlebox_username }}'
moodlebox_db_password: '{{ moodlebox_password }}'

# MoodleBox db root password.
moodlebox_db_root_password: '{{ moodlebox_password }}'

# MoodleBox Wi-Fi settings.
moodlebox_wifi_password: '{{ moodlebox_hostname }}'
moodlebox_wifi_ssid: '{{ moodlebox_name }}'
moodlebox_wifi_channel: '11'
moodlebox_wifi_country: 'CH'

# MoodleBox localisation parameters.
moodlebox_default_locale: 'en_GB.UTF-8'
moodlebox_locales:
  - 'en_GB.UTF-8'
  - 'en_AU.UTF-8'
  - 'fr_FR.UTF-8'
  - 'de_DE.UTF-8'
  - 'es_ES.UTF-8'
  - 'it_IT.UTF-8'
moodlebox_timezone: 'Europe/Zurich'

# Public key filename.
moodlebox_public_key_file: 'id_rsa.pub'

# MoodleBox release info filename.
moodlebox_info_file: 'moodlebox-info'

# MoodleBox logo filename.
moodlebox_logo_file: 'moodlebox-logo.txt'

# MoodleBox Moodle default build settings.
moodlebox_moodle_branch: 'MOODLE_310_STABLE'
moodlebox_moodle_username: 'moodlebox'
moodlebox_moodle_password: '{{ moodlebox_password }}'
moodlebox_moodle_db: 'moodle'
moodlebox_moodle_db_prefix: 'mdl_'
moodlebox_moodle_lang: 'en'
moodlebox_moodle_name: '{{ moodlebox_name }}'
moodlebox_moodle_summary: |
  <p><span lang='en' class='multilang'><a href='https://moodlebox.net/' target='_blank'>MoodleBox</a>, a <a href='https://moodle.org/' target='_blank'>Moodle 3.10.x</a> platform on <a href='https://www.raspberrypi.org/' target='_blank'>Raspberry Pi</a>.</span><span lang='fr' class='multilang'><a href='https://moodlebox.net/' target='_blank'>MoodleBox</a>, une plateforme <a href='https://moodle.org/' target='_blank'>Moodle 3.10.x</a> sur <a href='https://www.raspberrypi.org/' target='_blank'>Raspberry Pi</a>.</span><span lang='de' class='multilang'><a href='https://moodlebox.net/' target='_blank'>MoodleBox</a>, eine <a href='https://moodle.org/' target='_blank'>Moodle 3.10.x</a> Plattform auf <a href='https://www.raspberrypi.org/' target='_blank'>Raspberry Pi</a>.</span></p>
  <p><span lang='en' class='multilang'>MoodleBox is made by <a href='https://blog.martignoni.net/a-propos/'>Nicolas Martignoni</a>.</span><span lang='fr' class='multilang'>MoodleBox est réalisée par <a href='https://blog.martignoni.net/a-propos/'>Nicolas Martignoni</a>.</span><span lang='de' class='multilang'>MoodleBox ist von <a href='https://blog.martignoni.net/a-propos/'>Nicolas Martignoni</a> hergestellt.</span></p>
  <p><span lang='en' class='multilang'>Version {{ moodlebox_version }}, {{ moodlebox_release_date }}.</span><span lang='fr' class='multilang'>Version {{ moodlebox_version }}, {{ moodlebox_release_date }}.</span><span lang='de' class='multilang'>Version {{ moodlebox_version }}, {{ moodlebox_release_date }}.</span></p>
moodlebox_moodle_source_dir: '/var/www/moodle'
moodlebox_moodle_data_dir: '/var/www/moodledata'

# MoodleBox default build options.
moodlebox_update_firmware: 'false'
moodlebox_set_hostname: 'true'
moodlebox_set_timezone: 'true'
moodlebox_set_locale: 'true'
moodlebox_moodlebox_plugin_version: 'v2.8.0'
moodlebox_mathjax_version: '2.7.9'

moodlebox_build_type: 'release'

# Raspberry default credentials.
moodlebox_rpi_username: 'ubuntu'
moodlebox_rpi_password: 'Moodlebox4$'

# Raspberry default hostname.
moodlebox_rpi_hostname: 'ubuntu'
