---
- name: copy root CA certificate
  copy:
    src: 'home/files/moodleboxCA.crt'
    dest: '/home/{{ moodlebox_username }}/files/moodleboxCA.crt'
    owner: '{{ moodlebox_username }}'
    group: 'www-data'
    mode: '0644'
