---

- name: copy usbmount deb package file
  copy:
    src: 'usbmount_0.0.24_all.deb'
    dest: '/tmp/usbmount.deb'
    mode: '0644'

- name: install usbmount package
  apt:
    deb: '/tmp/usbmount.deb'

- name: delete usbmount deb package file
  file:
    path: '/tmp/usbmount.deb'
    state: 'absent'

- name: enable ntfs and exfat formats mounting by usbmount
  replace:
    path: '/etc/usbmount/usbmount.conf'
    regexp: '^FILESYSTEMS=.*$'
    replace: 'FILESYSTEMS="vfat exfat ntfs fuseblk ext2 ext3 ext4 hfsplus"'

- name: copy nodogsplash deb package file
  copy:
    src: 'nodogsplash_5.0.0-1_arm64.deb'
    dest: '/tmp/nodogsplash_5.0.0-1_arm64.deb'
    mode: '0644'

- name: install nodogsplash package
  apt:
    deb: '/tmp/nodogsplash_5.0.0-1_arm64.deb'

- name: delete nodogsplash deb package file
  file:
    path: '/tmp/nodogsplash_5.0.0-1_arm64.deb'
    state: 'absent'

- name: configure nodogsplash captive portal
  template:
    src: 'etc/nodogsplash/nodogsplash.conf.j2'
    dest: '/etc/nodogsplash/nodogsplash.conf'
    mode: '0644'

- name: disable nodogsplash service at startup
  systemd:
    name: 'nodogsplash'
    state: 'stopped'
    enabled: 'false'
    masked: 'false'

- name: remove default nodogsplash files
  file:
    path: '/etc/nodogsplash/htdocs'
    state: 'absent'

- name: update nodogsplash files
  copy:
    src: 'etc/nodogsplash/htdocs'
    dest: '/etc/nodogsplash'
    mode: '0644'

- name: add root to allowed incron users
  lineinfile:
    path: '/etc/incron.allow'
    line: 'root'
  notify: restart incron

- name: set umask for nginx and php-fpm services
  lineinfile:
    path: '{{ item }}'
    line: 'UMask=0002'
    insertafter: '^\[Service\].*'
  with_items:
    - '/lib/systemd/system/nginx.service'
    - '/lib/systemd/system/php7.4-fpm.service'
  notify: restart web services

- name: set 'group' of php-fpm process
  lineinfile:
    path: '/etc/php/7.4/fpm/pool.d/www.conf'
    regexp: '^group\s*=\s*www-data.*'
    line: 'group = {{ moodlebox_username }}'
  notify: restart web services

- name: set 'pm.max_requests' of php-fpm process
  lineinfile:
    path: '/etc/php/7.4/fpm/pool.d/www.conf'
    regexp: '^;?pm.max_requests\s*=.*'
    line: 'pm.max_requests = 50'
  notify: restart web services

- name: set 'emergency_restart_threshold' for php-fpm to fix SIGSEGV
  lineinfile:
    path: '/etc/php/7.4/fpm/php-fpm.conf'
    regexp: '^;?emergency_restart_threshold\s*=.*'
    line: 'emergency_restart_threshold = 2'
  notify: restart web services

- name: set 'emergency_restart_interval' for php-fpm to fix SIGSEGV
  lineinfile:
    path: '/etc/php/7.4/fpm/php-fpm.conf'
    regexp: '^;?emergency_restart_interval\s*=.*'
    line: 'emergency_restart_interval = 1h'
  notify: restart web services

- name: set 'process_control_timeout' for php-fpm to fix SIGSEGV
  lineinfile:
    path: '/etc/php/7.4/fpm/php-fpm.conf'
    regexp: '^;?process_control_timeout\s*=.*'
    line: 'process_control_timeout = 5s'
  notify: restart web services

- meta: flush_handlers
