---
- name: check if database for Moodle exists
  command: mysql -e 'SHOW DATABASES LIKE "{{ moodlebox_moodle_db }}"' -sN
  register: moodle_db_exists
  failed_when: moodle_db_exists.rc > 1
  changed_when: moodle_db_exists.rc == 0

- name: drop database for Moodle
  mysql_db:
    name: '{{ moodlebox_moodle_db }}'
    state: 'absent'
  when: moodle_db_exists is changed

- name: remove temporary storage for Moodle cache
  mount:
    name: '{{ item.name }}'
    state: 'unmounted'
  with_items:
    - { name: '/var/cache/moodle' }
    - { name: '{{ moodlebox_moodle_data_dir }}/temp' }
    - { name: '{{ moodlebox_moodle_data_dir }}/sessions' }

- name: remove previous Moodle installation data
  file:
    path: '{{ item }}'
    state: 'absent'
  with_items:
    - '{{ moodlebox_moodle_data_dir }}'
    - '{{ moodlebox_moodle_source_dir }}/config.php'
    - '/var/cache/moodle'
    - '/var/cache/moodle-cache-backup'

- name: check if any incron job exist
  shell: 'incrontab -l | wc -c'
  register: incronjob_exists
  changed_when: incronjob_exists.stdout|int > 0

- name: remove incron jobs
  command: 'incrontab -u root -r'
  when: incronjob_exists is changed
